zstyle :plugin:fast-syntax-highlighting theme "newtheme"
typeset -g FAST_THEME_NAME="newtheme"
: ${FAST_HIGHLIGHT_STYLES[newthemedefault]:=fg=white,bold,bg=8}
: ${FAST_HIGHLIGHT_STYLES[newthemeunknown-token]:=fg=red,bold}
: ${FAST_HIGHLIGHT_STYLES[newthemereserved-word]:=bold,fg=6}
: ${FAST_HIGHLIGHT_STYLES[newthemealias]:=fg=green}
: ${FAST_HIGHLIGHT_STYLES[newthemesuffix-alias]:=fg=green}
: ${FAST_HIGHLIGHT_STYLES[newthemebuiltin]:=fg=4,bold}
: ${FAST_HIGHLIGHT_STYLES[newthemefunction]:=fg=4,bold}
: ${FAST_HIGHLIGHT_STYLES[newthemecommand]:=fg=3,bold}
: ${FAST_HIGHLIGHT_STYLES[newthemeprecommand]:=fg=2}
: ${FAST_HIGHLIGHT_STYLES[newthemecommandseparator]:=none}
: ${FAST_HIGHLIGHT_STYLES[newthemehashed-command]:=fg=green}
: ${FAST_HIGHLIGHT_STYLES[newthemepath]:=fg=magenta}
: ${FAST_HIGHLIGHT_STYLES[newthemepath_pathseparator]:=}
: ${FAST_HIGHLIGHT_STYLES[newthemeglobbing]:=fg=blue,bold}
: ${FAST_HIGHLIGHT_STYLES[newthemeglobbing-ext]:=fg=13}
: ${FAST_HIGHLIGHT_STYLES[newthemehistory-expansion]:=fg=blue,bold}
: ${FAST_HIGHLIGHT_STYLES[newthemesingle-hyphen-option]:=fg=cyan}
: ${FAST_HIGHLIGHT_STYLES[newthemedouble-hyphen-option]:=fg=cyan}
: ${FAST_HIGHLIGHT_STYLES[newthemeback-quoted-argument]:=none}
: ${FAST_HIGHLIGHT_STYLES[newthemesingle-quoted-argument]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[newthemedouble-quoted-argument]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[newthemedollar-quoted-argument]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[newthemeback-or-dollar-double-quoted-argument]:=fg=cyan}
: ${FAST_HIGHLIGHT_STYLES[newthemeback-dollar-quoted-argument]:=fg=cyan}
: ${FAST_HIGHLIGHT_STYLES[newthemeassign]:=fg=10,bold}
: ${FAST_HIGHLIGHT_STYLES[newthemeredirection]:=none}
: ${FAST_HIGHLIGHT_STYLES[newthemecomment]:=fg=white,bold,bg=8}
: ${FAST_HIGHLIGHT_STYLES[newthemevariable]:=fg=2,bold}
: ${FAST_HIGHLIGHT_STYLES[newthememathvar]:=fg=blue,bold}
: ${FAST_HIGHLIGHT_STYLES[newthememathnum]:=fg=magenta}
: ${FAST_HIGHLIGHT_STYLES[newthemematherr]:=fg=red}
: ${FAST_HIGHLIGHT_STYLES[newthemeassign-array-bracket]:=fg=green}
: ${FAST_HIGHLIGHT_STYLES[newthemefor-loop-variable]:=none}
: ${FAST_HIGHLIGHT_STYLES[newthemefor-loop-number]:=fg=magenta}
: ${FAST_HIGHLIGHT_STYLES[newthemefor-loop-operator]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[newthemefor-loop-separator]:=fg=yellow,bold}
: ${FAST_HIGHLIGHT_STYLES[newthemeexec-descriptor]:=fg=yellow,bold}
: ${FAST_HIGHLIGHT_STYLES[newthemehere-string-tri]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[newthemehere-string-text]:=fg=18}
: ${FAST_HIGHLIGHT_STYLES[newthemehere-string-var]:=fg=cyan,bg=18}
: ${FAST_HIGHLIGHT_STYLES[newthemesecondary]:=default}
: ${FAST_HIGHLIGHT_STYLES[newthemecase-input]:=fg=green}
: ${FAST_HIGHLIGHT_STYLES[newthemecase-parentheses]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[newthemecase-condition]:=bg=blue}
: ${FAST_HIGHLIGHT_STYLES[newthemecorrect-subtle]:=fg=12}
: ${FAST_HIGHLIGHT_STYLES[newthemeincorrect-subtle]:=fg=red}
: ${FAST_HIGHLIGHT_STYLES[newthemesubtle-separator]:=fg=green}
: ${FAST_HIGHLIGHT_STYLES[newthemesubtle-bg]:=bg=18}
: ${FAST_HIGHLIGHT_STYLES[newthemepath-to-dir]:=fg=magenta,underline}
: ${FAST_HIGHLIGHT_STYLES[newthemepaired-bracket]:=fg=0,bg=14,bold}
: ${FAST_HIGHLIGHT_STYLES[newthemebracket-level-1]:=fg=66,bg=0,bold}
: ${FAST_HIGHLIGHT_STYLES[newthemebracket-level-2]:=fg=82,bg=0,bold}
: ${FAST_HIGHLIGHT_STYLES[newthemebracket-level-3]:=fg=98,bg=0,bold}
: ${FAST_HIGHLIGHT_STYLES[newthemeglobal-alias]:=bg=blue}
: ${FAST_HIGHLIGHT_STYLES[newthemesubcommand]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[newthemesingle-sq-bracket]:=fg=6,bg=0,bold}
: ${FAST_HIGHLIGHT_STYLES[newthemedouble-sq-bracket]:=fg=3,bg=0,bold}
: ${FAST_HIGHLIGHT_STYLES[newthemedouble-paren]:=fg=1,bg=0,bold}
: ${FAST_HIGHLIGHT_STYLES[newthemeoptarg-string]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[newthemeoptarg-number]:=fg=magenta}
: ${FAST_HIGHLIGHT_STYLES[newthemerecursive-base]:=fg=16}
