daemonize = true          # run as a traditional UNIX daemon
max_history = 250          # max clip history limit
log_level = 'DEBUG'        # log level

[monitor]
load_current = true       # load current clipboard content at startup
enable_clipboard = true   # watch X11 clipboard
enable_primary = true     # watch X11 primary clipboard
filter_min_size = 1

[grpc]
host = '127.0.0.1'        # host address for gRPC
port = 45045              # port number for gRPC
